<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Bradford Assay | Biostatistics Portfolio I</title>
  <meta name="description" content="Chapter 4 Bradford Assay | Biostatistics Portfolio I" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Bradford Assay | Biostatistics Portfolio I" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Bradford Assay | Biostatistics Portfolio I" />
  
  
  

<meta name="author" content="Dr. F.J. Rodenburg   © 2020–2021 Universiteit Leiden" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="mendelian-genetics.html"/>
<link rel="next" href="your-own-experiment-i.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Biostatistics Portfolio I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>1</b> Installation</a>
<ul>
<li class="chapter" data-level="1.1" data-path="installation.html"><a href="installation.html#installation-guide"><i class="fa fa-check"></i><b>1.1</b> Installation Guide</a>
<ul>
<li class="chapter" data-level="" data-path="installation.html"><a href="installation.html#note-about-tinytex"><i class="fa fa-check"></i>Note about TinyTeX</a></li>
<li class="chapter" data-level="" data-path="installation.html"><a href="installation.html#note-about-installation-problems"><i class="fa fa-check"></i>Note about installation problems</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="installation.html"><a href="installation.html#the-rstudio-interface"><i class="fa fa-check"></i><b>1.2</b> The RStudio interface</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html"><i class="fa fa-check"></i><b>2</b> Basic Programming Tutorials</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html#swirl"><i class="fa fa-check"></i><b>2.1</b> <code>swirl</code></a></li>
<li class="chapter" data-level="2.2" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html#learnr"><i class="fa fa-check"></i><b>2.2</b> <code>learnr</code> (*)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html"><i class="fa fa-check"></i><b>3</b> Mendelian Genetics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#corn-example"><i class="fa fa-check"></i><b>3.1</b> Corn Example</a>
<ul>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#cornex1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-2"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#cornchisq"><i class="fa fa-check"></i><b>3.2</b> Chi-Squared Test</a>
<ul>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-3"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-4"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-5-optional"><i class="fa fa-check"></i>Exercise 5 (optional)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="bradford-assay.html"><a href="bradford-assay.html"><i class="fa fa-check"></i><b>4</b> Bradford Assay</a>
<ul>
<li class="chapter" data-level="4.1" data-path="bradford-assay.html"><a href="bradford-assay.html#what-is-a-bradford-assay"><i class="fa fa-check"></i><b>4.1</b> What Is a Bradford Assay?</a></li>
<li class="chapter" data-level="4.2" data-path="bradford-assay.html"><a href="bradford-assay.html#how-to-contruct-a-bsa-curve-in-r"><i class="fa fa-check"></i><b>4.2</b> How to Contruct a BSA-Curve in R</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="bradford-assay.html"><a href="bradford-assay.html#enterdata"><i class="fa fa-check"></i><b>4.2.1</b> Enter your data</a></li>
<li class="chapter" data-level="4.2.2" data-path="bradford-assay.html"><a href="bradford-assay.html#fitBSA"><i class="fa fa-check"></i><b>4.2.2</b> Fit a Simple Linear Model</a></li>
<li class="chapter" data-level="4.2.3" data-path="bradford-assay.html"><a href="bradford-assay.html#plot-your-data-draw-a-line"><i class="fa fa-check"></i><b>4.2.3</b> Plot your data &amp; draw a line</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="bradford-assay.html"><a href="bradford-assay.html#using-a-bradford-assay-for-estimation"><i class="fa fa-check"></i><b>4.3</b> Using a Bradford Assay for Estimation</a></li>
<li class="chapter" data-level="4.4" data-path="bradford-assay.html"><a href="bradford-assay.html#howprecise"><i class="fa fa-check"></i><b>4.4</b> How Precise Is the Estimate?</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bradford-assay.html"><a href="bradford-assay.html#r-squared"><i class="fa fa-check"></i><b>4.4.1</b> R-squared</a></li>
<li class="chapter" data-level="4.4.2" data-path="bradford-assay.html"><a href="bradford-assay.html#prediction-interval"><i class="fa fa-check"></i><b>4.4.2</b> Prediction interval</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="bradford-assay.html"><a href="bradford-assay.html#improveyourfigure"><i class="fa fa-check"></i><b>4.5</b> Improving Your Figure (*)</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="bradford-assay.html"><a href="bradford-assay.html#improving-the-main-plot"><i class="fa fa-check"></i><b>4.5.1</b> Improving the main plot</a></li>
<li class="chapter" data-level="4.5.2" data-path="bradford-assay.html"><a href="bradford-assay.html#highlighting-the-line"><i class="fa fa-check"></i><b>4.5.2</b> Highlighting the line</a></li>
<li class="chapter" data-level="4.5.3" data-path="bradford-assay.html"><a href="bradford-assay.html#adding-a-grid"><i class="fa fa-check"></i><b>4.5.3</b> Adding a grid</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="bradford-assay.html"><a href="bradford-assay.html#alternative-method"><i class="fa fa-check"></i><b>4.6</b> Alternative Method (*)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html"><i class="fa fa-check"></i><b>5</b> Your Own Experiment I</a>
<ul>
<li class="chapter" data-level="5.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#study-design"><i class="fa fa-check"></i><b>5.2</b> Study Design</a></li>
<li class="chapter" data-level="5.3" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#why-use-a-statistical-test"><i class="fa fa-check"></i><b>5.3</b> Why Use a Statistical Test?</a></li>
<li class="chapter" data-level="5.4" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#how-do-statistical-tests-work"><i class="fa fa-check"></i><b>5.4</b> How Do Statistical Tests Work?</a></li>
<li class="chapter" data-level="5.5" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#chi-squared"><i class="fa fa-check"></i><b>5.5</b> The Chi-Squared Test</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#how-does-the-chi-squared-test-work"><i class="fa fa-check"></i><b>5.5.1</b> How Does the Chi-Squared Test Work?</a></li>
<li class="chapter" data-level="5.5.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#chisq"><i class="fa fa-check"></i><b>5.5.2</b> Chi-Squared Test in R</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#microbiologyex"><i class="fa fa-check"></i><b>5.6</b> Exercises</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#performing-a-chi-squared-test"><i class="fa fa-check"></i><b>5.6.1</b> Performing a Chi-Squared Test</a></li>
<li class="chapter" data-level="5.6.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#compare2"><i class="fa fa-check"></i><b>5.6.2</b> Comparing Two Students</a></li>
<li class="chapter" data-level="5.6.3" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#comparing-two-other-students"><i class="fa fa-check"></i><b>5.6.3</b> Comparing Two Other Students</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sepia.html"><a href="sepia.html"><i class="fa fa-check"></i><b>6</b> Sepia</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sepia.html"><a href="sepia.html#getting-started"><i class="fa fa-check"></i><b>6.1</b> Getting Started</a></li>
<li class="chapter" data-level="6.2" data-path="sepia.html"><a href="sepia.html#plotting-the-data"><i class="fa fa-check"></i><b>6.2</b> Plotting the Data</a></li>
<li class="chapter" data-level="6.3" data-path="sepia.html"><a href="sepia.html#creating-a-subset"><i class="fa fa-check"></i><b>6.3</b> Creating a Subset</a></li>
<li class="chapter" data-level="6.4" data-path="sepia.html"><a href="sepia.html#t-test"><i class="fa fa-check"></i><b>6.4</b> T-test</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="sepia.html"><a href="sepia.html#sepiatest"><i class="fa fa-check"></i><b>6.4.1</b> Example</a></li>
<li class="chapter" data-level="6.4.2" data-path="sepia.html"><a href="sepia.html#exercise"><i class="fa fa-check"></i><b>6.4.2</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html"><i class="fa fa-check"></i><b>7</b> Your Own Experiment II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html#study-design-1"><i class="fa fa-check"></i><b>7.1</b> Study Design</a></li>
<li class="chapter" data-level="7.2" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html#preparing-your-presentation"><i class="fa fa-check"></i><b>7.2</b> Preparing Your Presentation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html"><i class="fa fa-check"></i>Adding Figures in R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#image-from-a-file-simple"><i class="fa fa-check"></i>Image from a File (simple)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-1"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#image-from-a-file-advanced"><i class="fa fa-check"></i>Image from a File (advanced)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-2-1"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#plots-drawn-in-r"><i class="fa fa-check"></i>Plots Drawn in R</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#simple-example-linear-relationship"><i class="fa fa-check"></i>Simple Example (Linear Relationship)</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#multplot"><i class="fa fa-check"></i>Multiple Plots in One Area</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-3-1"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-4-1"><i class="fa fa-check"></i>Exercise 4 (*)</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-5"><i class="fa fa-check"></i>Exercise 5 (*)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html"><i class="fa fa-check"></i>Adding Tables in R Markdown</a>
<ul>
<li><a href="adding-tables-in-r-markdown.html#the-user-friendly-way-kable">The User-Friendly Way: <code>kable</code></a>
<ul>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exercise-1-1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exT.2"><i class="fa fa-check"></i>Exercise 2 (*)</a></li>
</ul></li>
<li><a href="adding-tables-in-r-markdown.html#advanced-xtable">Advanced: <code>xtable</code> (*)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exercise-3-2"><i class="fa fa-check"></i>Exercise 3 (*)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Biostatistics Portfolio I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bradford-assay" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Bradford Assay</h1>
<p><small><b><i>Date:</b> 2/3 November 2021</p>
<p><b>Topic:</b> Estimation, Prediction</p>
<p><b>Duration:</b> 30–90 min.</i></small></p>
<hr />
<p>In this chapter you will learn how to conduct a Bradford assay for estimating the amount of protein present in a sample.</p>
<p><b>From this chapter on, you will collect all your analyses into a portfolio</b>. This is simply an R markdown file that you knit to Word at the end of each chapter. At the start of the statistics course at the end of the academic year, your portfolio should contain all the exercises of chapters 4–6.</p>
<p>Remember, to make a <a href="https://youtu.be/2Sovzf6lVRo?t=280">new R markdown file</a>, go to <strong>File</strong> &gt; <strong>New File</strong> &gt; <strong>R markdown</strong>. Then select Word and press OK.</p>
<div id="what-is-a-bradford-assay" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> What Is a Bradford Assay?</h2>
<p>In the basic practicals you will use a spectrophotometer to measure light passing through a sample with a known protein concentration. By doing so for various concentrations of protein, you can construct a curve for the amount of protein present in a sample, given the amount of light passing through. This is a basic tool in biological experimentation. The protein used as a reference to construct the curve is called Bovine Serum Albumin (BSA).<a href="references.html#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> Hence the name: <em>BSA curve</em>.</p>
<p><small></p>
<table style="width:50%;">
<caption>
<span id="tab:ExampleBSA">Table 4.1: </span>Example data of a BSA experiment. As more protein is present in the sample, less light passes through and so the <span class="math inline">\(\text{A}_{595}\)</span> increases.
</caption>
<thead>
<tr>
<th style="text-align:center;">
BSA <span class="math inline">\((\mu\text{g})\)</span>
</th>
<th style="text-align:center;">
Absorption <span class="math inline">\((\text{A}_{595})\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.000
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0.135
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0.235
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
0.328
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
0.409
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
0.495
</td>
</tr>
</tbody>
</table>
<p></small></p>
<div class="figure"><span style="display:block;" id="fig:typicalBSA"></span>
<img src="Biostatistics_files/figure-html/typicalBSA-1.png" alt="A typical BSA curve, constructed from the data in table \@ref(tab:ExampleBSA)." width="100%" />
<p class="caption">
Figure 4.1: A typical BSA curve, constructed from the data in table <a href="bradford-assay.html#tab:ExampleBSA">4.1</a>.
</p>
</div>
<p>In the first part of this assignment, you will construct a BSA-curve based on your experimental data. In the second half, we are going to express the uncertainty of the estimation.</p>
</div>
<div id="how-to-contruct-a-bsa-curve-in-r" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> How to Contruct a BSA-Curve in R</h2>
<p>As an example, I will show you how to construct a BSA curve from the data shown in table <a href="bradford-assay.html#tab:ExampleBSA">4.1</a>.</p>
<div id="enterdata" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Enter your data</h3>
<p>First we create a data frame containing the BSA amounts and the observed <span class="math inline">\(\text{A}_{595}\)</span> values.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="bradford-assay.html#cb3-1" aria-hidden="true" tabindex="-1"></a>BSA  <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb3-2"><a href="bradford-assay.html#cb3-2" aria-hidden="true" tabindex="-1"></a>A595 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.135</span>, <span class="fl">0.235</span>, <span class="fl">0.328</span>, <span class="fl">0.409</span>, <span class="fl">0.495</span>)</span>
<span id="cb3-3"><a href="bradford-assay.html#cb3-3" aria-hidden="true" tabindex="-1"></a>DF   <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(BSA, A595)</span></code></pre></div>
<p>This will create an object <code>DF</code> in the object space. You can view it by clicking on it in the environment tab of the upper-right pane in RStudio.</p>
</div>
<div id="fitBSA" class="section level3" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Fit a Simple Linear Model</h3>
<p>Watch the first two minutes of <a href="https://youtu.be/3PAAB3VDmFQ">this video</a> on simple linear regression.</p>
<p><strong>Question</strong>:</p>
<ol style="list-style-type: decimal">
<li>A Bradford assay shows a [positive / negative] linear relationship between the amount of protein and the absorbance. <em>(Choose one.)</em></li>
<li>Describe in your own words what intercept &amp; slope mean.</li>
<li>Enter your data in R as shown <a href="bradford-assay.html#enterdata">above</a>, using <em>your own</em> experimental data.</li>
<li>Estimate the intercept and slope as follows:</li>
</ol>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="bradford-assay.html#cb4-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(A595 <span class="sc">~</span> BSA, <span class="at">data =</span> DF)</span></code></pre></div>
<p>How that works will be explained in the statistics course. For now, let’s extract the intercept and slope from this model:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="bradford-assay.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model)</span></code></pre></div>
<pre><code>## (Intercept)         BSA 
##  0.02485714  0.09685714</code></pre>
<p>In this example, the estimated line pretty much goes through the origin,<a href="references.html#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> with an intercept of about 0.02. We can also see that there is a positive linear relationship between the amount of BSA and the absorbance: For every microgram of BSA added, the absorbance increases by about 0.1.</p>
<p><strong>Question</strong>:</p>
<ol start="5" style="list-style-type: decimal">
<li>What are the intercept and slope of <em>your</em> experimental data?</li>
</ol>
</div>
<div id="plot-your-data-draw-a-line" class="section level3" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Plot your data &amp; draw a line</h3>
<p>Finally we create a plot and add a line as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="bradford-assay.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(A595 <span class="sc">~</span> BSA, <span class="at">data =</span> DF)</span>
<span id="cb7-2"><a href="bradford-assay.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">coef</span>(model))</span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>As you can see in the example here, though it looks a bit basic, this is all you need to produce a BSA curve. Of course you can <a href="bradford-assay.html#improveyourfigure">improve your figure</a> if you want, by using more advanced plotting routines.</p>
<p><strong>Question</strong>:</p>
<ol start="6" style="list-style-type: decimal">
<li>Create the plot shown above using your own experimental data.</li>
</ol>
</div>
</div>
<div id="using-a-bradford-assay-for-estimation" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Using a Bradford Assay for Estimation</h2>
<p>Let’s say you measured the absorbance of the sample of interest and ended up with a value of <span class="math inline">\(\text{A}_{595} = 0.264\)</span>. Using the BSA curve, you can estimate the amount of protein as shown in the figure below:</p>
<div class="figure"><span style="display:block;" id="fig:estimateBSA"></span>
<img src="Biostatistics_files/figure-html/estimateBSA-1.png" alt="\label{fig:estimateBSA}To estimate the amount of protein, look at the $\text{A}_{595}$ on the y-axis, then see which position it corresponds to on the x-axis." width="672" />
<p class="caption">
Figure 4.2: To estimate the amount of protein, look at the <span class="math inline">\(\text{A}_{595}\)</span> on the y-axis, then see which position it corresponds to on the x-axis.
</p>
</div>
<p>Apparently the sample of interest has the same absorbance as a BSA sample of about <span class="math inline">\(2.5\)</span> microgram.</p>
<p>If you want a more precise estimate, you have to use the equation of the model we just fitted:</p>
<p><span class="math display" id="eq:BSAlinear">\[\begin{equation}
\text{A}_{595} = \text{intercept} + \text{slope}\times\text{BSA}
\tag{4.1}
\end{equation}\]</span></p>
<p>If we fill in the example, we get:</p>
<p><span class="math display">\[
\begin{aligned}
0.264 &amp;= 0.02485714 + 0.09685714 \times \text{BSA} + 0 \\
\\
\text{BSA} &amp;= \frac{0.264 - 0.02485714}{0.09685714} \approx 2.47
\end{aligned}
\]</span></p>
<p>Which is approximately equal to the <span class="math inline">\(2.5\)</span> we read from figure <a href="bradford-assay.html#fig:estimateBSA">4.2</a>.</p>
<p><strong>Question</strong>:</p>
<ol start="7" style="list-style-type: decimal">
<li>Can you read from your own figure the amount of protein in the sample of interest?</li>
<li>Perform the estimation using eq. <a href="bradford-assay.html#eq:BSAlinear">(4.1)</a> with your own BSA curve and your own observed absorbance:
<ul>
<li>If you have performed the experiment twice or more, you can average the absorbance for a more precise answer;</li>
<li>Make sure to adjust for any dilution you applied to the sample.</li>
</ul></li>
</ol>
</div>
<div id="howprecise" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> How Precise Is the Estimate?</h2>
<p>I’m sure you’ve noticed that the observations do not exactly fall on the line. The regression model is but an approximation of the true relationship. This is caused by many things:</p>
<ul>
<li>No matter how careful you are, the amount of BSA cannot be weighed <em>exactly</em>;</li>
<li>The spectrophotometer does not have infinite precision;</li>
<li>Any dilutions applied can introduce small errors;</li>
<li>The true relationship is probably not <em>perfectly</em> linear.</li>
</ul>
<p>It is more than likely that if you perform the experiment again, you will obtain slightly different values. Even if you take great care, <strong>there is <em>always</em> uncertainty</strong>. At best, you can keep that uncertainty low.</p>
<p>So how much uncertainty is there? How do we express that? Below I will discuss a simple measure to include in your plot, and a great way to visualize the uncertainty.</p>
<div id="r-squared" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> R-squared</h3>
<p><span class="math inline">\(R^2\)</span> is the amount of variance explained by the model. In other words: How much of the total variance in <span class="math inline">\(\text{A}_{595}\)</span> can be explained by the line?</p>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The red segments on the right represent the original spread in <span class="math inline">\(\text{A}_{595}\)</span>,<a href="references.html#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a> and on the right we see the spread that is left after accounting for our model. You can clearly see that the distances on the right are <em>much</em> smaller than on the left. If you square these segments and sum them, that is called the <em>variance</em>. <span class="math inline">\(R^2\)</span> is then calculated as:</p>
<p><span class="math display">\[R^2 = 1 - \frac{\text{remaining variance}}{\text{total variance}}\]</span></p>
<p>R includes this value in the <code>summary</code> of a linear model by default. You can obtain it as follows:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="bradford-assay.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.9913461</code></pre>
<p>Apparently the BSA curve explains around <span class="math inline">\(99.1\%\)</span> of the total variance in absorbance. This is quite a large amount: Only <span class="math inline">\(0.9\%\)</span> of the variance is unexplained. A higher <span class="math inline">\(R^2\)</span> value means there is less uncertainty.</p>
<p><strong>Question</strong>:</p>
<ol start="9" style="list-style-type: decimal">
<li>What is the value of <span class="math inline">\(R^2\)</span> using your own experimental data?</li>
<li>How could you obtain a higher <span class="math inline">\(R^2\)</span>?</li>
</ol>
</div>
<div id="prediction-interval" class="section level3" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Prediction interval</h3>
<p>Where would you expect 95% of the future observations of <span class="math inline">\(\text{A}_{595}\)</span> to be? That is the question a 95% prediction interval answers. Though its calculation is beyond the scope of this chapter, generating such an interval along the BSA curve in R can be done in a few lines of code:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="bradford-assay.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(A595 <span class="sc">~</span> BSA, <span class="at">data =</span> DF)</span>
<span id="cb10-2"><a href="bradford-assay.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">coef</span>(model))</span>
<span id="cb10-3"><a href="bradford-assay.html#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="bradford-assay.html#cb10-4" aria-hidden="true" tabindex="-1"></a>newX  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">BSA =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">5</span>, <span class="fl">0.1</span>)) <span class="co"># 0.0, 0.1, ..., 4.9, 5.0</span></span>
<span id="cb10-5"><a href="bradford-assay.html#cb10-5" aria-hidden="true" tabindex="-1"></a>newY  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">predict</span>(model, newX, <span class="at">interval =</span> <span class="st">&quot;predict&quot;</span>))</span>
<span id="cb10-6"><a href="bradford-assay.html#cb10-6" aria-hidden="true" tabindex="-1"></a>newDF <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newX, newY)</span>
<span id="cb10-7"><a href="bradford-assay.html#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="bradford-assay.html#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(lwr <span class="sc">~</span> BSA, <span class="at">data =</span> newDF) <span class="co"># lower bound of the interval</span></span>
<span id="cb10-9"><a href="bradford-assay.html#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(upr <span class="sc">~</span> BSA, <span class="at">data =</span> newDF) <span class="co"># upper bound of the interval</span></span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p><strong>Question</strong>:</p>
<ol start="11" style="list-style-type: decimal">
<li>Produce a prediction interval for your own BSA curve? Try it by copying the code above and <a href="bradford-assay.html#improveyourfigure">adjusting it</a> if you like.</li>
<li>Figure <a href="bradford-assay.html#fig:estimateBSA">4.2</a> showed how to estimate the protein concentration of a sample of interest. Now that you have a prediction interval around the line, within which values do you expect the protein concentration to be?</li>
</ol>
</div>
</div>
<div id="improveyourfigure" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Improving Your Figure (*)</h2>
<p>In the examples so far, I tried to keep the coding part simple. Here I will show how to reproduce the figure by expanding the code a bit. You can use whichever parts you like and change it. Using a hashtag (<code>#</code>), I will provide comments after each line to explain what it’s for. For additional tips on improving figures and adding them to your portfolio, see the chapter on <a href="adding-figures-in-r-markdown.html#adding-figures-in-r-markdown">adding figures</a>.</p>
<div id="improving-the-main-plot" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Improving the main plot</h3>
<p>Using some tricks described in the help page of <code>plotmath</code>, you can add proper annotation to your axes:</p>
<p><small></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="bradford-assay.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb11-2"><a href="bradford-assay.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  A595 <span class="sc">~</span> BSA, <span class="at">data =</span> DF,           <span class="co"># A595 vs BSA, from data set DF</span></span>
<span id="cb11-3"><a href="bradford-assay.html#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">&quot;BSA Curve&quot;</span>,              <span class="co"># Title</span></span>
<span id="cb11-4"><a href="bradford-assay.html#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">&quot;Protein (μg/ml)&quot;</span>,        <span class="co"># X-axis annotation</span></span>
<span id="cb11-5"><a href="bradford-assay.html#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="fu">bquote</span>(A[<span class="dv">595</span>]),           <span class="co"># Y-axis annotation</span></span>
<span id="cb11-6"><a href="bradford-assay.html#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch  =</span> <span class="dv">19</span>,                       <span class="co"># Solid point character (see ?pch)</span></span>
<span id="cb11-7"><a href="bradford-assay.html#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">las  =</span> <span class="dv">1</span>                         <span class="co"># Set label style to horizontal</span></span>
<span id="cb11-8"><a href="bradford-assay.html#cb11-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p></small></p>
</div>
<div id="highlighting-the-line" class="section level3" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Highlighting the line</h3>
<p>For emphasis, I changed the width and color of the line:</p>
<p><small></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="bradford-assay.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add this *after* your call to the plot function. Then run both.</span></span>
<span id="cb12-2"><a href="bradford-assay.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(</span>
<span id="cb12-3"><a href="bradford-assay.html#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(model),      <span class="co"># Coefficients from the object &#39;model&#39;</span></span>
<span id="cb12-4"><a href="bradford-assay.html#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>,          <span class="co"># Increase line width to 2 (default 1)</span></span>
<span id="cb12-5"><a href="bradford-assay.html#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">&quot;steelblue&quot;</span> <span class="co"># Change the color of the line</span></span>
<span id="cb12-6"><a href="bradford-assay.html#cb12-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p></small></p>
</div>
<div id="adding-a-grid" class="section level3" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> Adding a grid</h3>
<p>You can add a grid if you like. If you do, keep these three things in mind:</p>
<ul>
<li><strong>Don’t use <code>grid</code></strong>. This function is so dumb even its help page admits you’re better off using <code>abline(h = ..., v = ...)</code>:</li>
</ul>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-19"></span>
<img src="Biostatistics_files/figure-html/unnamed-chunk-19-1.png" alt="Look closely at how the grid meets the axes on the left..." width="672" />
<p class="caption">
Figure 4.3: Look closely at how the grid meets the axes on the left…
</p>
</div>
<p><small></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="bradford-assay.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bad example:</span></span>
<span id="cb13-2"><a href="bradford-assay.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(A595 <span class="sc">~</span> BSA, <span class="at">data =</span> DF, <span class="at">main =</span> <span class="st">&quot;wow great job, grid...&quot;</span>)</span>
<span id="cb13-3"><a href="bradford-assay.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>(<span class="at">nx =</span> <span class="dv">5</span>, <span class="at">ny =</span> <span class="dv">5</span>)</span>
<span id="cb13-4"><a href="bradford-assay.html#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">coef</span>(model))</span>
<span id="cb13-5"><a href="bradford-assay.html#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="bradford-assay.html#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Good example:</span></span>
<span id="cb13-7"><a href="bradford-assay.html#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(A595 <span class="sc">~</span> BSA, <span class="at">data =</span> DF, <span class="at">main =</span> <span class="st">&quot;abline to the rescue&quot;</span>)</span>
<span id="cb13-8"><a href="bradford-assay.html#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="fl">0.1</span>), <span class="at">v =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">col =</span> <span class="st">&quot;lightgray&quot;</span>)</span>
<span id="cb13-9"><a href="bradford-assay.html#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">coef</span>(model))</span></code></pre></div>
<p></small></p>
<ul>
<li>Some prefer light on dark, others dark on light. I don’t mind either way. But <strong>avoid using a high contrast</strong> for your grid. It is not the main subject being plotted and should fall into the background:</li>
</ul>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-21"></span>
<img src="Biostatistics_files/figure-html/unnamed-chunk-21-1.png" alt="A grid should have low contrast to avoid crowding the plot." width="672" />
<p class="caption">
Figure 4.4: A grid should have low contrast to avoid crowding the plot.
</p>
</div>
<p style="margin-left: 32px">
To add a colored background to your plot, insert the following line after the call to <code>plot</code>:
</p>
<p><small></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="bradford-assay.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add this *after* your call to the plot function.</span></span>
<span id="cb14-2"><a href="bradford-assay.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(<span class="fu">par</span>(<span class="st">&quot;usr&quot;</span>)[<span class="dv">1</span>], <span class="fu">par</span>(<span class="st">&quot;usr&quot;</span>)[<span class="dv">3</span>], <span class="fu">par</span>(<span class="st">&quot;usr&quot;</span>)[<span class="dv">2</span>], <span class="fu">par</span>(<span class="st">&quot;usr&quot;</span>)[<span class="dv">4</span>], <span class="at">col =</span> <span class="st">&quot;grey90&quot;</span>)</span></code></pre></div>
<p></small></p>
<p style="margin-left: 32px">
Then draw your grid in white:
</p>
<p><small></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="bradford-assay.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add this *after* your call to the rect function.</span></span>
<span id="cb15-2"><a href="bradford-assay.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="fl">0.1</span>), <span class="at">v =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">col =</span> <span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<p></small></p>
<ul>
<li>When adding anything to a base R plot, R draws on top of the existing plot. That means it looks more professional if you <strong>redraw the points on top of the rest</strong>. Your full code for the plot then looks something like this:</li>
</ul>
<p><small></p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="bradford-assay.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coordinate system:</span></span>
<span id="cb16-2"><a href="bradford-assay.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb16-3"><a href="bradford-assay.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  A595 <span class="sc">~</span> BSA, <span class="at">data =</span> DF, </span>
<span id="cb16-4"><a href="bradford-assay.html#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">&quot;BSA Curve&quot;</span>,</span>
<span id="cb16-5"><a href="bradford-assay.html#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">&quot;Protein (μg/ml)&quot;</span>,</span>
<span id="cb16-6"><a href="bradford-assay.html#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="fu">bquote</span>(A[<span class="dv">595</span>]),</span>
<span id="cb16-7"><a href="bradford-assay.html#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">las  =</span> <span class="dv">1</span></span>
<span id="cb16-8"><a href="bradford-assay.html#cb16-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-9"><a href="bradford-assay.html#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="bradford-assay.html#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Background:</span></span>
<span id="cb16-11"><a href="bradford-assay.html#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(<span class="fu">par</span>(<span class="st">&quot;usr&quot;</span>)[<span class="dv">1</span>], <span class="fu">par</span>(<span class="st">&quot;usr&quot;</span>)[<span class="dv">3</span>], <span class="fu">par</span>(<span class="st">&quot;usr&quot;</span>)[<span class="dv">2</span>], <span class="fu">par</span>(<span class="st">&quot;usr&quot;</span>)[<span class="dv">4</span>], <span class="at">col =</span> <span class="st">&quot;grey90&quot;</span>)</span>
<span id="cb16-12"><a href="bradford-assay.html#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="bradford-assay.html#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Grid:</span></span>
<span id="cb16-14"><a href="bradford-assay.html#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="fl">0.1</span>), <span class="at">v =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">col =</span> <span class="st">&quot;white&quot;</span>)</span>
<span id="cb16-15"><a href="bradford-assay.html#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="bradford-assay.html#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co"># BSA curve:</span></span>
<span id="cb16-17"><a href="bradford-assay.html#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">coef</span>(model), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;steelblue&quot;</span>)</span>
<span id="cb16-18"><a href="bradford-assay.html#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="bradford-assay.html#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Observations redrawn:</span></span>
<span id="cb16-20"><a href="bradford-assay.html#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(A595 <span class="sc">~</span> BSA, <span class="at">data =</span> DF, <span class="at">pch =</span> <span class="dv">19</span>)</span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p></small></p>
</div>
</div>
<div id="alternative-method" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Alternative Method (*)</h2>
<p>It is a bit awkward to first fit a model that predicts the <span class="math inline">\(\text{A}_{595}\)</span>, and then invert the formula to obtain predictions for the amount of protein, like we did with eq. <a href="bradford-assay.html#eq:BSAlinear">(4.1)</a>. Unfortunately, this is the standard procedure in biology.</p>
<ol start="13" style="list-style-type: decimal">
<li>In this optional exercise, you are going to do it the correct way from a statistical point of view:</li>
</ol>
<ul>
<li>Start from <a href="bradford-assay.html#fitBSA">the beginning</a> and fit a linear model where the amount of protein is the outcome, rather than the absorbance (<code>lm(BSA ~ A595, data = DF)</code>);</li>
<li>Go through the chapter again, adjusting the code where needed with this inverted model;</li>
<li>Does your prediction differ from the previous one? Why do you think that happens?</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="mendelian-genetics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="your-own-experiment-i.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Biostatistics.pdf", "Biostatistics.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
