<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Sepia | Biostatistics Portfolio I</title>
  <meta name="description" content="Chapter 6 Sepia | Biostatistics Portfolio I" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Sepia | Biostatistics Portfolio I" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Sepia | Biostatistics Portfolio I" />
  
  
  

<meta name="author" content="Dr. F.J. Rodenburg   © 2020–2021 Universiteit Leiden" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="your-own-experiment-i.html"/>
<link rel="next" href="your-own-experiment-ii.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Biostatistics Portfolio I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>1</b> Installation</a>
<ul>
<li class="chapter" data-level="1.1" data-path="installation.html"><a href="installation.html#installation-guide"><i class="fa fa-check"></i><b>1.1</b> Installation Guide</a>
<ul>
<li class="chapter" data-level="" data-path="installation.html"><a href="installation.html#note-about-tinytex"><i class="fa fa-check"></i>Note about TinyTeX</a></li>
<li class="chapter" data-level="" data-path="installation.html"><a href="installation.html#note-about-installation-problems"><i class="fa fa-check"></i>Note about installation problems</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="installation.html"><a href="installation.html#the-rstudio-interface"><i class="fa fa-check"></i><b>1.2</b> The RStudio interface</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html"><i class="fa fa-check"></i><b>2</b> Basic Programming Tutorials</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html#swirl"><i class="fa fa-check"></i><b>2.1</b> <code>swirl</code></a></li>
<li class="chapter" data-level="2.2" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html#learnr"><i class="fa fa-check"></i><b>2.2</b> <code>learnr</code> (*)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html"><i class="fa fa-check"></i><b>3</b> Mendelian Genetics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#corn-example"><i class="fa fa-check"></i><b>3.1</b> Corn Example</a>
<ul>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#cornex1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-2"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#cornchisq"><i class="fa fa-check"></i><b>3.2</b> Chi-Squared Test</a>
<ul>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-3"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-4"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-5-optional"><i class="fa fa-check"></i>Exercise 5 (optional)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="bradford-assay.html"><a href="bradford-assay.html"><i class="fa fa-check"></i><b>4</b> Bradford Assay</a>
<ul>
<li class="chapter" data-level="4.1" data-path="bradford-assay.html"><a href="bradford-assay.html#what-is-a-bradford-assay"><i class="fa fa-check"></i><b>4.1</b> What Is a Bradford Assay?</a></li>
<li class="chapter" data-level="4.2" data-path="bradford-assay.html"><a href="bradford-assay.html#how-to-contruct-a-bsa-curve-in-r"><i class="fa fa-check"></i><b>4.2</b> How to Contruct a BSA-Curve in R</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="bradford-assay.html"><a href="bradford-assay.html#enterdata"><i class="fa fa-check"></i><b>4.2.1</b> Enter your data</a></li>
<li class="chapter" data-level="4.2.2" data-path="bradford-assay.html"><a href="bradford-assay.html#fitBSA"><i class="fa fa-check"></i><b>4.2.2</b> Fit a Simple Linear Model</a></li>
<li class="chapter" data-level="4.2.3" data-path="bradford-assay.html"><a href="bradford-assay.html#plot-your-data-draw-a-line"><i class="fa fa-check"></i><b>4.2.3</b> Plot your data &amp; draw a line</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="bradford-assay.html"><a href="bradford-assay.html#using-a-bradford-assay-for-estimation"><i class="fa fa-check"></i><b>4.3</b> Using a Bradford Assay for Estimation</a></li>
<li class="chapter" data-level="4.4" data-path="bradford-assay.html"><a href="bradford-assay.html#howprecise"><i class="fa fa-check"></i><b>4.4</b> How Precise Is the Estimate?</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bradford-assay.html"><a href="bradford-assay.html#r-squared"><i class="fa fa-check"></i><b>4.4.1</b> R-squared</a></li>
<li class="chapter" data-level="4.4.2" data-path="bradford-assay.html"><a href="bradford-assay.html#prediction-interval"><i class="fa fa-check"></i><b>4.4.2</b> Prediction interval</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="bradford-assay.html"><a href="bradford-assay.html#improveyourfigure"><i class="fa fa-check"></i><b>4.5</b> Improving Your Figure (*)</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="bradford-assay.html"><a href="bradford-assay.html#improving-the-main-plot"><i class="fa fa-check"></i><b>4.5.1</b> Improving the main plot</a></li>
<li class="chapter" data-level="4.5.2" data-path="bradford-assay.html"><a href="bradford-assay.html#highlighting-the-line"><i class="fa fa-check"></i><b>4.5.2</b> Highlighting the line</a></li>
<li class="chapter" data-level="4.5.3" data-path="bradford-assay.html"><a href="bradford-assay.html#adding-a-grid"><i class="fa fa-check"></i><b>4.5.3</b> Adding a grid</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="bradford-assay.html"><a href="bradford-assay.html#alternative-method"><i class="fa fa-check"></i><b>4.6</b> Alternative Method (*)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html"><i class="fa fa-check"></i><b>5</b> Your Own Experiment I</a>
<ul>
<li class="chapter" data-level="5.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#study-design"><i class="fa fa-check"></i><b>5.2</b> Study Design</a></li>
<li class="chapter" data-level="5.3" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#why-use-a-statistical-test"><i class="fa fa-check"></i><b>5.3</b> Why Use a Statistical Test?</a></li>
<li class="chapter" data-level="5.4" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#how-do-statistical-tests-work"><i class="fa fa-check"></i><b>5.4</b> How Do Statistical Tests Work?</a></li>
<li class="chapter" data-level="5.5" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#chi-squared"><i class="fa fa-check"></i><b>5.5</b> The Chi-Squared Test</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#how-does-the-chi-squared-test-work"><i class="fa fa-check"></i><b>5.5.1</b> How Does the Chi-Squared Test Work?</a></li>
<li class="chapter" data-level="5.5.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#chisq"><i class="fa fa-check"></i><b>5.5.2</b> Chi-Squared Test in R</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#microbiologyex"><i class="fa fa-check"></i><b>5.6</b> Exercises</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#performing-a-chi-squared-test"><i class="fa fa-check"></i><b>5.6.1</b> Performing a Chi-Squared Test</a></li>
<li class="chapter" data-level="5.6.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#compare2"><i class="fa fa-check"></i><b>5.6.2</b> Comparing Two Students</a></li>
<li class="chapter" data-level="5.6.3" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#comparing-two-other-students"><i class="fa fa-check"></i><b>5.6.3</b> Comparing Two Other Students</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sepia.html"><a href="sepia.html"><i class="fa fa-check"></i><b>6</b> Sepia</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sepia.html"><a href="sepia.html#getting-started"><i class="fa fa-check"></i><b>6.1</b> Getting Started</a></li>
<li class="chapter" data-level="6.2" data-path="sepia.html"><a href="sepia.html#data-cleaning"><i class="fa fa-check"></i><b>6.2</b> Data Cleaning</a></li>
<li class="chapter" data-level="6.3" data-path="sepia.html"><a href="sepia.html#plotting-the-data"><i class="fa fa-check"></i><b>6.3</b> Plotting the Data</a></li>
<li class="chapter" data-level="6.4" data-path="sepia.html"><a href="sepia.html#creating-a-subset"><i class="fa fa-check"></i><b>6.4</b> Creating a Subset</a></li>
<li class="chapter" data-level="6.5" data-path="sepia.html"><a href="sepia.html#t-test"><i class="fa fa-check"></i><b>6.5</b> T-test</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="sepia.html"><a href="sepia.html#sepiatest"><i class="fa fa-check"></i><b>6.5.1</b> Example</a></li>
<li class="chapter" data-level="6.5.2" data-path="sepia.html"><a href="sepia.html#exercise"><i class="fa fa-check"></i><b>6.5.2</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html"><i class="fa fa-check"></i><b>7</b> Your Own Experiment II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html#study-design-1"><i class="fa fa-check"></i><b>7.1</b> Study Design</a></li>
<li class="chapter" data-level="7.2" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html#preparing-your-presentation"><i class="fa fa-check"></i><b>7.2</b> Preparing Your Presentation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html"><i class="fa fa-check"></i>Adding Figures in R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#image-from-a-file-simple"><i class="fa fa-check"></i>Image from a File (simple)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-1"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#image-from-a-file-advanced"><i class="fa fa-check"></i>Image from a File (advanced)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-2-1"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#plots-drawn-in-r"><i class="fa fa-check"></i>Plots Drawn in R</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#simple-example-linear-relationship"><i class="fa fa-check"></i>Simple Example (Linear Relationship)</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#multplot"><i class="fa fa-check"></i>Multiple Plots in One Area</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-3-1"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-4-1"><i class="fa fa-check"></i>Exercise 4 (*)</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-5"><i class="fa fa-check"></i>Exercise 5 (*)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html"><i class="fa fa-check"></i>Adding Tables in R Markdown</a>
<ul>
<li><a href="adding-tables-in-r-markdown.html#the-user-friendly-way-kable">The User-Friendly Way: <code>kable</code></a>
<ul>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exercise-1-1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exT.2"><i class="fa fa-check"></i>Exercise 2 (*)</a></li>
</ul></li>
<li><a href="adding-tables-in-r-markdown.html#advanced-xtable">Advanced: <code>xtable</code> (*)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exercise-3-2"><i class="fa fa-check"></i>Exercise 3 (*)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Biostatistics Portfolio I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sepia" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Sepia</h1>
<p><small><b><i>Date:</b> 16/17 March 2022 (Animal Biodiversity course)</p>
<p><b>Topic:</b> Data manipulation, <span class="math inline">\(t\)</span>-test</p>
<p><b>Duration:</b> 60–90 minutes</i></small></p>
<hr />
<p><img src="figures/Sepia.png" width="1000" /></p>
<p>Does the common cuttlefish (<em>Sepia officinalis</em>) display sexual dimorphism? Are males perhaps taller or wider? In this chapter, you are going to scientifically compare two groups of measurements.</p>
<div id="getting-started" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Getting Started</h2>
<p>The first step is to correctly read your data into the software:</p>
<iframe src="https://www.youtube.com/embed/BGUqZc-Pb8w" width="672" height="400px" data-external="1">
</iframe>
<ol style="list-style-type: decimal">
<li>If you haven’t already, <a href="installation.html#installation">install RStudio</a>;</li>
<li>Download the data. If it is an Excel (.xlsx) file, open it in Excel and <a href="https://youtu.be/BGUqZc-Pb8w?t=21">save as CSV</a>;</li>
<li>Open RStudio and <a href="https://youtu.be/2Sovzf6lVRo?t=280">create a new R markdown file</a>. <strong>Save this file to the same folder as the data!</strong></li>
<li>Go to <strong>Session</strong> &gt; <strong>Set Working Directory</strong> &gt; <strong>To Source File Location</strong>. R now knows where to locate your data;</li>
<li><a href="https://youtu.be/AHAR7j-IUOw?t=357">Create a new code chunk</a> and run the following:</li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="sepia.html#cb1-1" aria-hidden="true" tabindex="-1"></a>Sepia <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Sepia.csv&quot;</span>)</span></code></pre></div>
<p>From here on out, just read the text, run the code in R, adjust the R code if needed, and answer the questions.</p>
<p><font color = "red"><b>Note</b></font>: For the sake of privacy, this page uses an old version of the data with scrambled names. I have also not linked the actual data. Please ask an assistant if you are unable to find it. The scrambled version can be downloaded <a href="data/Sepia.csv">here</a>.</p>
<hr />
<p>If the code ran successfully, you will have an object called <code>Sepia</code> in your workspace. You can view it by clicking it, or by running:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="sepia.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(Sepia)</span></code></pre></div>
<p>Rather than type long names throughout the analysis, let’s make the variable names a bit shorter:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="sepia.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(Sepia) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Name&quot;</span>, <span class="st">&quot;Affix&quot;</span>, <span class="st">&quot;Surname&quot;</span>, <span class="st">&quot;TableNr&quot;</span>, <span class="st">&quot;Group&quot;</span>, <span class="st">&quot;Length&quot;</span>, <span class="st">&quot;Width&quot;</span>, <span class="st">&quot;Sex&quot;</span>, <span class="st">&quot;Type&quot;</span>)</span></code></pre></div>
<p>Does R understand which variables are numbers and which are something else? Let’s check:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="sepia.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Sepia)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    24 obs. of  9 variables:
##  $ Name   : chr  &quot;nltCllt&quot; &quot;dilHH&quot; &quot;mEmE&quot; &quot;rrtM&quot; ...
##  $ Affix  : chr  &quot;&quot; &quot;&quot; &quot;&quot; &quot;&quot; ...
##  $ Surname: chr  &quot;kakkBe&quot; &quot;zuoztHeta&quot; &quot;tronnC&quot; &quot;dnodrenaal&quot; ...
##  $ TableNr: int  1 4 1 1 8 7 2 2 4 9 ...
##  $ Group  : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ Length : chr  &quot;150&quot; &quot;78&quot; &quot;170&quot; &quot;93&quot; ...
##  $ Width  : chr  &quot;56&quot; &quot;31&quot; &quot;64&quot; &quot;31&quot; ...
##  $ Sex    : chr  &quot;man&quot; &quot;vrouwelijk&quot; &quot;vrouwelijk&quot; &quot;vrouwelijk&quot; ...
##  $ Type   : int  2 3 NA 3 NA 2 3 2 NA 3 ...</code></pre>
<p><strong>Question</strong>:</p>
<ol style="list-style-type: decimal">
<li>Is the data read correctly into R? How can you tell?</li>
<li>What do you think <code>chr</code> and <code>int</code> mean?</li>
</ol>
</div>
<div id="data-cleaning" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Data Cleaning</h2>
<p>Even though length and width are numeric values, R says they are not. This is because there are some non-numeric values filled in in the fields for length and width. Let’s fix that:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="sepia.html#cb6-1" aria-hidden="true" tabindex="-1"></a>Sepia<span class="sc">$</span>Length <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(Sepia<span class="sc">$</span>Length)</span>
<span id="cb6-2"><a href="sepia.html#cb6-2" aria-hidden="true" tabindex="-1"></a>Sepia<span class="sc">$</span>Width <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(Sepia<span class="sc">$</span>Width)</span></code></pre></div>
<p>This will produce a warning, informing you that some values have been overwritten. Those were actually the values that said “geen schelp”, so this is correct.</p>
<p>There is another issue we have to fix:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="sepia.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Sepia<span class="sc">$</span>Sex)</span></code></pre></div>
<pre><code>## [1] &quot;man&quot;         &quot;vrouwelijk&quot;  &quot;mannelijk&quot;   &quot;&quot;            &quot;vrouwelijk &quot;
## [6] &quot;Mannelijk&quot;</code></pre>
<p>Students were not consistent with the use of wording. But your computer is not very smart, it expects VERY precise input. You could fix this manually, but here is a faster way:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="sepia.html#cb9-1" aria-hidden="true" tabindex="-1"></a>isMale              <span class="ot">&lt;-</span> <span class="fu">grepl</span>(<span class="st">&quot;m&quot;</span>, <span class="fu">tolower</span>(Sepia<span class="sc">$</span>Sex))</span>
<span id="cb9-2"><a href="sepia.html#cb9-2" aria-hidden="true" tabindex="-1"></a>isFemale            <span class="ot">&lt;-</span> <span class="fu">grepl</span>(<span class="st">&quot;v&quot;</span>, <span class="fu">tolower</span>(Sepia<span class="sc">$</span>Sex))</span>
<span id="cb9-3"><a href="sepia.html#cb9-3" aria-hidden="true" tabindex="-1"></a>Sepia<span class="sc">$</span>Sex           <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb9-4"><a href="sepia.html#cb9-4" aria-hidden="true" tabindex="-1"></a>Sepia<span class="sc">$</span>Sex[isMale]   <span class="ot">&lt;-</span> <span class="st">&quot;M&quot;</span></span>
<span id="cb9-5"><a href="sepia.html#cb9-5" aria-hidden="true" tabindex="-1"></a>Sepia<span class="sc">$</span>Sex[isFemale] <span class="ot">&lt;-</span> <span class="st">&quot;F&quot;</span></span>
<span id="cb9-6"><a href="sepia.html#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Sepia<span class="sc">$</span>Sex)</span></code></pre></div>
<pre><code>## [1] &quot;M&quot; &quot;F&quot; NA</code></pre>
<p>So… why did that work?</p>
<ul>
<li><code>grepl</code> searches for a pattern in a string.</li>
<li>In the first line, I search for a lower-case “m”, because that only appears in the variations of the Dutch word for “male”.</li>
<li>Some students may have used capital letters, so first I convert all strings to lower-case characters.</li>
<li>In the second line, I use the same trick and search for “v”.</li>
<li>In the third line, I overwrite all values with <code>NA</code> (not available).</li>
<li>In the fourth line, I fill in a capital letter “M” where I know the observations are male.</li>
<li>In the fifth line, I fill in a capital letter “F” where I know the observations are female.</li>
</ul>
<p>Other than that, you did a fairly good job. The only extra piece of data cleaning I can think of at this point is the observations with very large table numbers:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="sepia.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(Sepia<span class="sc">$</span>TableNr)</span></code></pre></div>
<pre><code>##  [1]  1  1  1  1  2  2  2  3  4  4  6  6  6  6  7  7  7  8  8  8  9  9 54 98</code></pre>
<p>I don’t think there are 98 tables in the practical room. You can overwrite a particular value like this:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="sepia.html#cb13-1" aria-hidden="true" tabindex="-1"></a>Sepia<span class="sc">$</span>TableNr[Sepia<span class="sc">$</span>TableNr <span class="sc">==</span> <span class="dv">98</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<p>Do you know the right table number for this observation? Then you can replace <code>NA</code> by the number you think it should be.</p>
<ol start="3" style="list-style-type: decimal">
<li>There is at least one outlier in the data. Can you identify it from the plot? If you believe this value to be really this large, leave it as it (you can ask the students that measured it). If you don’t trust this observation, you can set it to <code>NA</code> as shown above.</li>
</ol>
</div>
<div id="plotting-the-data" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Plotting the Data</h2>
<p>Just looking at code and numbers is a bit stale. So let’s make some relevant plots:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="sepia.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># Plot in a 2x2 grid</span></span>
<span id="cb14-2"><a href="sepia.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Sepia<span class="sc">$</span>Length, <span class="at">col =</span> <span class="st">&quot;lightgray&quot;</span>)</span>
<span id="cb14-3"><a href="sepia.html#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Sepia<span class="sc">$</span>Width, <span class="at">col =</span> <span class="st">&quot;lightgray&quot;</span>)</span>
<span id="cb14-4"><a href="sepia.html#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Length <span class="sc">~</span> Width, <span class="at">data =</span> Sepia, <span class="at">col =</span> <span class="fu">factor</span>(Sex))</span>
<span id="cb14-5"><a href="sepia.html#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Width <span class="sc">~</span> Sex, <span class="at">data =</span> Sepia, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>))</span>
<span id="cb14-6"><a href="sepia.html#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)) <span class="co"># Restore the default</span></span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p><strong>Question</strong>:</p>
<ol start="4" style="list-style-type: decimal">
<li>What does each plot show?</li>
<li>Can you change the code to alter the figurees? <em>(You can try changing the variable names, or change the graphical parameters.)</em></li>
</ol>
</div>
<div id="creating-a-subset" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Creating a Subset</h2>
<p>We just read the whole data set. It contains the data from all groups Let’s make a <em>subset</em> of the measurements performed by table 1, group 1:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="sepia.html#cb15-1" aria-hidden="true" tabindex="-1"></a>Subset <span class="ot">&lt;-</span> Sepia[Sepia<span class="sc">$</span>TableNr <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> Sepia<span class="sc">$</span>Group <span class="sc">==</span> <span class="dv">1</span>, ]</span></code></pre></div>
<p>What does this code do?</p>
<ul>
<li><code>Subset &lt;-</code>: Create a variable named <code>Subset</code>;</li>
<li><code>Sepia[x, y]</code>: From the data set <code>Sepia</code>, select only rows <code>x</code> and columns <code>y</code>. If <code>y</code> is left blank, it selects all columns;<a href="references.html#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></li>
<li><code>Sepia$Groep == "A"</code>: From the data set <code>Sepia</code>, select the variable <code>Group</code> and check if it is equal to the value <code>A</code> (<code>TRUE</code>) or not (<code>FALSE</code>).</li>
</ul>
<p><strong>Question</strong>:</p>
<ol start="6" style="list-style-type: decimal">
<li>Adapt the code above to create a subset of measurements of the type of <em>Sepia</em> you measured (1, 2, or 3) and your group (1 or 2).</li>
</ol>
</div>
<div id="t-test" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> T-test</h2>
<p>How do we compare measurements of two groups? One way to do that is through a <span class="math inline">\(t\)</span>-test. To choose the right <span class="math inline">\(t\)</span>-test, you should understand five choices:</p>
<ul>
<li>Do you need a one-sample, or two-sample <span class="math inline">\(t\)</span>-test?</li>
<li>Do you want to test one-sided or two-sided?</li>
<li>Is it reasonable to assume equal variance?</li>
<li>Are the measurements independent or paired?</li>
<li>Is the underlying assumption of normality reasonable?</li>
</ul>
<p>Do you remember all of those choices? Is so, impressive! If not, you can <strong>rewatch the video version</strong> of the lecture here:</p>
<iframe src="https://www.youtube.com/embed/qJA3CvFt_pc" width="672" height="400px" data-external="1">
</iframe>
<div id="sepiatest" class="section level3" number="6.5.1">
<h3><span class="header-section-number">6.5.1</span> Example</h3>
<p>Below is an <strong>example</strong> of a <span class="math inline">\(t\)</span>-test, using some standard data in R:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="sepia.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(extra <span class="sc">~</span> group, <span class="at">data =</span> sleep, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  extra by group
## t = -1.8608, df = 18, p-value = 0.03959
## alternative hypothesis: true difference in means between group 1 and group 2 is less than 0
## 95 percent confidence interval:
##        -Inf -0.1076222
## sample estimates:
## mean in group 1 mean in group 2 
##            0.75            2.33</code></pre>
<p>This particular <span class="math inline">\(t\)</span>-test is a one-sided <span class="math inline">\(t\)</span>-test for equal variance. Here’s how to interpret the output: The mean of group 1 is <span class="math inline">\(0.75\)</span> hours of extra sleep, while the mean of group 2 is <span class="math inline">\(2.33\)</span>. The <span class="math inline">\(p\)</span>-value for this test is <span class="math inline">\(0.0396\)</span>. If we use a level of significance of <span class="math inline">\(\alpha = 0.05\)</span>, then group 2 is has a significantly larger mean than group 1, because <span class="math inline">\(0.0396 &lt; 0.05\)</span>.</p>
</div>
<div id="exercise" class="section level3" number="6.5.2">
<h3><span class="header-section-number">6.5.2</span> Exercise</h3>
<p><strong>Question</strong>:</p>
<p>Choose a <span class="math inline">\(t\)</span>-test you deem appropriate for:</p>
<ol start="7" style="list-style-type: decimal">
<li>Comparing male and female length;</li>
<li>Comparing male and female width.</li>
</ol>
<p><em>(They could be the same, just explain briefly why you chose a certain <span class="math inline">\(t\)</span>-test.)</em></p>
<p><strong>Question</strong>:</p>
<ol start="9" style="list-style-type: decimal">
<li>Perform the tests you chose for (1) and (2) in R and draw a conclusion. Have a look at how <a href="sepia.html#sepiatest">the example</a> was coded using the <code>data</code> argument and adjust it to make it work for the data of your group (<code>Subset</code>). You may use the same level of significance <span class="math inline">\(\alpha = 0.05\)</span>.</li>
<li>Compare your results with at least one other group. If your conclusion differs, can you explain why?</li>
<li>Did we now prove that <em>Sepia</em> males and females differ in physical dimensions? Did we prove they are the same? What is the right way to express the conclusion?</li>
<li>(Optional) You performed two tests. That means that both can result in a false positive. With <span class="math inline">\(\alpha = 0.05\)</span>, what is the chance of at least one false positive when performing two tests?</li>
</ol>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="your-own-experiment-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="your-own-experiment-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Biostatistics.pdf", "Biostatistics.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
