<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Your Own Experiment I | Biostatistics Portfolio I</title>
  <meta name="description" content="Chapter 5 Your Own Experiment I | Biostatistics Portfolio I" />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Your Own Experiment I | Biostatistics Portfolio I" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Your Own Experiment I | Biostatistics Portfolio I" />
  
  
  

<meta name="author" content="Dr. F.J. Rodenburg   © 2020–2022 Universiteit Leiden" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="bradford-assay.html"/>
<link rel="next" href="sepia.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Biostatistics Portfolio I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>1</b> Installation</a>
<ul>
<li class="chapter" data-level="1.1" data-path="installation.html"><a href="installation.html#installation-guide"><i class="fa fa-check"></i><b>1.1</b> Installation Guide</a>
<ul>
<li class="chapter" data-level="" data-path="installation.html"><a href="installation.html#note-about-tinytex"><i class="fa fa-check"></i>Note about TinyTeX</a></li>
<li class="chapter" data-level="" data-path="installation.html"><a href="installation.html#note-about-installation-problems"><i class="fa fa-check"></i>Note about installation problems</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="installation.html"><a href="installation.html#the-rstudio-interface"><i class="fa fa-check"></i><b>1.2</b> The RStudio interface</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html"><i class="fa fa-check"></i><b>2</b> Basic Programming Tutorials</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html#swirl"><i class="fa fa-check"></i><b>2.1</b> <code>swirl</code></a></li>
<li class="chapter" data-level="2.2" data-path="basic-programming-tutorials.html"><a href="basic-programming-tutorials.html#learnr"><i class="fa fa-check"></i><b>2.2</b> <code>learnr</code> (*)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html"><i class="fa fa-check"></i><b>3</b> Mendelian Genetics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#corn-example"><i class="fa fa-check"></i><b>3.1</b> Corn Example</a>
<ul>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#cornex1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-2"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#cornchisq"><i class="fa fa-check"></i><b>3.2</b> Chi-Squared Test</a>
<ul>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-3"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-4"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="mendelian-genetics.html"><a href="mendelian-genetics.html#exercise-5-optional"><i class="fa fa-check"></i>Exercise 5 (optional)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="bradford-assay.html"><a href="bradford-assay.html"><i class="fa fa-check"></i><b>4</b> Bradford Assay</a>
<ul>
<li class="chapter" data-level="4.1" data-path="bradford-assay.html"><a href="bradford-assay.html#what-is-a-bradford-assay"><i class="fa fa-check"></i><b>4.1</b> What Is a Bradford Assay?</a></li>
<li class="chapter" data-level="4.2" data-path="bradford-assay.html"><a href="bradford-assay.html#how-to-contruct-a-bsa-curve-in-r"><i class="fa fa-check"></i><b>4.2</b> How to Contruct a BSA-Curve in R</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="bradford-assay.html"><a href="bradford-assay.html#enterdata"><i class="fa fa-check"></i><b>4.2.1</b> Enter your data</a></li>
<li class="chapter" data-level="4.2.2" data-path="bradford-assay.html"><a href="bradford-assay.html#fitBSA"><i class="fa fa-check"></i><b>4.2.2</b> Fit a Simple Linear Model</a></li>
<li class="chapter" data-level="4.2.3" data-path="bradford-assay.html"><a href="bradford-assay.html#plot-your-data-draw-a-line"><i class="fa fa-check"></i><b>4.2.3</b> Plot your data &amp; draw a line</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="bradford-assay.html"><a href="bradford-assay.html#using-a-bradford-assay-for-estimation"><i class="fa fa-check"></i><b>4.3</b> Using a Bradford Assay for Estimation</a></li>
<li class="chapter" data-level="4.4" data-path="bradford-assay.html"><a href="bradford-assay.html#howprecise"><i class="fa fa-check"></i><b>4.4</b> How Precise Is the Estimate?</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bradford-assay.html"><a href="bradford-assay.html#r-squared"><i class="fa fa-check"></i><b>4.4.1</b> R-squared</a></li>
<li class="chapter" data-level="4.4.2" data-path="bradford-assay.html"><a href="bradford-assay.html#prediction-interval"><i class="fa fa-check"></i><b>4.4.2</b> Prediction interval</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="bradford-assay.html"><a href="bradford-assay.html#improveyourfigure"><i class="fa fa-check"></i><b>4.5</b> Improving Your Figure (*)</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="bradford-assay.html"><a href="bradford-assay.html#improving-the-main-plot"><i class="fa fa-check"></i><b>4.5.1</b> Improving the main plot</a></li>
<li class="chapter" data-level="4.5.2" data-path="bradford-assay.html"><a href="bradford-assay.html#highlighting-the-line"><i class="fa fa-check"></i><b>4.5.2</b> Highlighting the line</a></li>
<li class="chapter" data-level="4.5.3" data-path="bradford-assay.html"><a href="bradford-assay.html#adding-a-grid"><i class="fa fa-check"></i><b>4.5.3</b> Adding a grid</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="bradford-assay.html"><a href="bradford-assay.html#alternative-method"><i class="fa fa-check"></i><b>4.6</b> Alternative Method (*)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html"><i class="fa fa-check"></i><b>5</b> Your Own Experiment I</a>
<ul>
<li class="chapter" data-level="5.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#study-design"><i class="fa fa-check"></i><b>5.2</b> Study Design</a></li>
<li class="chapter" data-level="5.3" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#why-use-a-statistical-test"><i class="fa fa-check"></i><b>5.3</b> Why Use a Statistical Test?</a></li>
<li class="chapter" data-level="5.4" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#how-do-statistical-tests-work"><i class="fa fa-check"></i><b>5.4</b> How Do Statistical Tests Work?</a></li>
<li class="chapter" data-level="5.5" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#chi-squared"><i class="fa fa-check"></i><b>5.5</b> The Chi-Squared Test</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#how-does-the-chi-squared-test-work"><i class="fa fa-check"></i><b>5.5.1</b> How Does the Chi-Squared Test Work?</a></li>
<li class="chapter" data-level="5.5.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#chisq"><i class="fa fa-check"></i><b>5.5.2</b> Chi-Squared Test in R</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#microbiologyex"><i class="fa fa-check"></i><b>5.6</b> Exercises</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#performing-a-chi-squared-test"><i class="fa fa-check"></i><b>5.6.1</b> Performing a Chi-Squared Test</a></li>
<li class="chapter" data-level="5.6.2" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#compare2"><i class="fa fa-check"></i><b>5.6.2</b> Comparing Two Students</a></li>
<li class="chapter" data-level="5.6.3" data-path="your-own-experiment-i.html"><a href="your-own-experiment-i.html#comparing-two-other-students"><i class="fa fa-check"></i><b>5.6.3</b> Comparing Two Other Students</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sepia.html"><a href="sepia.html"><i class="fa fa-check"></i><b>6</b> Sepia</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sepia.html"><a href="sepia.html#getting-started"><i class="fa fa-check"></i><b>6.1</b> Getting Started</a></li>
<li class="chapter" data-level="6.2" data-path="sepia.html"><a href="sepia.html#creating-a-subset"><i class="fa fa-check"></i><b>6.2</b> Creating a Subset</a></li>
<li class="chapter" data-level="6.3" data-path="sepia.html"><a href="sepia.html#data-cleaning"><i class="fa fa-check"></i><b>6.3</b> Data Cleaning</a></li>
<li class="chapter" data-level="6.4" data-path="sepia.html"><a href="sepia.html#plotting-the-data"><i class="fa fa-check"></i><b>6.4</b> Plotting the Data</a></li>
<li class="chapter" data-level="6.5" data-path="sepia.html"><a href="sepia.html#t-test"><i class="fa fa-check"></i><b>6.5</b> T-test</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="sepia.html"><a href="sepia.html#sepiatest"><i class="fa fa-check"></i><b>6.5.1</b> Example</a></li>
<li class="chapter" data-level="6.5.2" data-path="sepia.html"><a href="sepia.html#exercise"><i class="fa fa-check"></i><b>6.5.2</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html"><i class="fa fa-check"></i><b>7</b> Your Own Experiment II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html#study-design-1"><i class="fa fa-check"></i><b>7.1</b> Study Design</a></li>
<li class="chapter" data-level="7.2" data-path="your-own-experiment-ii.html"><a href="your-own-experiment-ii.html#preparing-your-presentation"><i class="fa fa-check"></i><b>7.2</b> Preparing Your Presentation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html"><i class="fa fa-check"></i>Adding Figures in R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#image-from-a-file-simple"><i class="fa fa-check"></i>Image from a File (simple)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-1"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#image-from-a-file-advanced"><i class="fa fa-check"></i>Image from a File (advanced)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-2-1"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#plots-drawn-in-r"><i class="fa fa-check"></i>Plots Drawn in R</a>
<ul>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#simple-example-linear-relationship"><i class="fa fa-check"></i>Simple Example (Linear Relationship)</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#multplot"><i class="fa fa-check"></i>Multiple Plots in One Area</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-3-1"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-4-1"><i class="fa fa-check"></i>Exercise 4 (*)</a></li>
<li class="chapter" data-level="" data-path="adding-figures-in-r-markdown.html"><a href="adding-figures-in-r-markdown.html#exercise-5"><i class="fa fa-check"></i>Exercise 5 (*)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html"><i class="fa fa-check"></i>Adding Tables in R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#the-user-friendly-way-kable"><i class="fa fa-check"></i>The User-Friendly Way: <code>kable</code></a>
<ul>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exercise-1-1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exT.2"><i class="fa fa-check"></i>Exercise 2 (*)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#advanced-xtable"><i class="fa fa-check"></i>Advanced: <code>xtable</code> (*)</a>
<ul>
<li class="chapter" data-level="" data-path="adding-tables-in-r-markdown.html"><a href="adding-tables-in-r-markdown.html#exercise-3-2"><i class="fa fa-check"></i>Exercise 3 (*)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Biostatistics Portfolio I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="your-own-experiment-i" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Your Own Experiment I<a href="your-own-experiment-i.html#your-own-experiment-i" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><small><b><i>Date:</b> 10 December 2021 (Microbiology course)</p>
<p><b>Topic:</b> Study design, hypothesis testing</p>
<p><b>Duration:</b> Up to you.</i></small></p>
<hr />
<p>In this chapter, I will walk you through the different ways you can setup an experiment that can be analyzed by a <span class="math inline">\(\chi^2\)</span>-test, or some variant of it. You have already used this test at least once, during the practical on <a href="mendelian-genetics.html#mendelian-genetics">Mendelian genetics</a>.</p>
<p>For the purpose of the course, <strong>you are free to design your own experiment</strong>, but I do recommend you avoid complicating the study design. If you have an idea for an experiment, ask an assistant or your teacher for approval.</p>
<div id="introduction" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Introduction<a href="your-own-experiment-i.html#introduction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is the explanation for first year biology students taking the microbiology course at Leiden University. The portfolio exercise itself is described <a href="your-own-experiment-i.html#microbiologyex">all the way at the end</a>.</p>
<p>The first exercise uses an example data set. In the second exercise, you are to use your own experimental data.</p>
</div>
<div id="study-design" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Study Design<a href="your-own-experiment-i.html#study-design" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the microbiology assignment, you will design your own experiment, perform an analysis, draw conclusions and report your findings. That is a lot of work, so start planning in time!</p>
<p>Designing a study requires consideration of both biology and statistics: What question is the study supposed to answer? What kind of test or model is able to do so? What are the independent experimental units?<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a> How large should your sample size be?</p>
<p>To make it all feasible within the context of your microbiology course, let’s restrict ourselves to one particular kind of comparison: Differences in counts among groups. For example:</p>
<ul>
<li>Is there a difference in the number of bacterial colonies counted on agar plates exposed to the air for an hour in the kitchen and the living room?</li>
</ul>
<p>The experiment then looks something like this:</p>
<p><img src="figures/MicrobiologyStudyDesign.png" width="100%" /></p>
<p>Feel free to come up with your own variation, but ask a course assistant or your teacher whether your research question is valid (and feasible). Also note that a more complex comparison may require a more elaborate study design and analysis! Try and keep it simple.</p>
<p>If you stick to bacterial counts in different groups, you can use a <span class="math inline">\(\chi^2\)</span>-squared test for the analysis, and a single agar plate per group. The <span class="math inline">\(\chi^2\)</span>-squared test is <a href="your-own-experiment-i.html#chi-squared">explained below</a>, using an example data set.</p>
</div>
<div id="why-use-a-statistical-test" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Why Use a Statistical Test?<a href="your-own-experiment-i.html#why-use-a-statistical-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You could simply count the number of colonies on each plate, determine the differences and be done with it. So what’s the appeal of a statistical test?</p>
<p>In the example research question, we compare the number of bacterial colonies after exposure to different conditions (kitchen, living room). There are uncountably many potential influences that we cannot (perfectly) measure, or control. Think of:</p>
<ul>
<li>The amount of medium on each plate will always differ slightly;</li>
<li>Temperature, humidity, airflow, and the amount of sunlight cannot be controlled precisely, but can be expected to affect the number of live bacteria falling onto the plate;</li>
<li>Storage and transportation conditions can be logically expected to affect growth;</li>
<li>Bacteria from your hand or breath might fall onto the plate, rather than bacteria floating in the air of the kitchen/living room;</li>
<li>The number of bacteria in the air is likely to depend on the last time someone used the kitchen, the ventilation hood and any nearby windows;</li>
<li>Low concentration bacteria in the air either will, or will not enter the plate by chance;</li>
<li>You would probably count a different number of bacteria, had you chosen a different moment, or position in the kitchen.</li>
</ul>
<p>And there are many other potential influences. Therefore, the exact count is hardly interesting. We aren’t so much interested in <em>whether</em> there is a difference, but rather whether there is large enough difference to be considered significant. A statistical test can help you decide on this.</p>
<p>Ideally, we would use a large number of replicates, so that we are not looking at the effect of a single, outlying observation (e.g. a particularly dirty kitchen). Therefore, in a later chapter we will reflect on the results of all students combined, and how we can best analyze those.</p>
</div>
<div id="how-do-statistical-tests-work" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> How Do Statistical Tests Work?<a href="your-own-experiment-i.html#how-do-statistical-tests-work" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A statistical test works by taking on a statement of no difference and then collecting evidence against it.</p>
<p>This statement of no difference is called the null-hypothesis (<span class="math inline">\(H_0\)</span>). If there is sufficient evidence against it, the null-hypothesis is rejected. What consitutes ‘enough’ evidence depends on what is considered an acceptable chance of a false positive (<span class="math inline">\(\alpha\)</span>):</p>
<ul>
<li><strong>Null-hypothesis (<span class="math inline">\(H_0\)</span>)</strong>: A statement of no difference;</li>
<li><strong>Level of significance (<span class="math inline">\(\alpha\)</span>)</strong>: What is an acceptable chance of a false positive?<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a></li>
</ul>
<p>When counting bacterial colonies on plates from two plates, the null-hypothesis would be:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> There is no difference in the number of bacterial colonies on either plate.</li>
</ul>
<p>A false positive would mean that you conclude a significant difference, even though the null-hypothesis is true. This can always happen, because a sample is just a random draw from the population,<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a> and can coincidentally be different from its population.</p>
<p>So which value should you choose for the level of significance (<span class="math inline">\(\alpha\)</span>)? That depends on your research:</p>
<ul>
<li>If we’re developing a diagnostic test for cancer, then a false positive could mean a a very serious operation for the patient. This means we have to be very strict about false positives. Even <span class="math inline">\(\alpha = 0.01\)</span> would mean <span class="math inline">\(\frac{1}{100}\)</span> healthy individuals would wrongly undergo treatment;<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a></li>
<li>If we’re just counting bacteria in kitchens and living rooms, a false positive is not that consequential, and we can be less strict about what is significant.</li>
</ul>
<p>Specifically, that means you could choose whatever value for <span class="math inline">\(\alpha\)</span> you want. However, in biological journals, it is convention to go no higher than <span class="math inline">\(\alpha = 0.05\)</span>. That implies a chance of <span class="math inline">\(5\%\)</span>, or <span class="math inline">\(\frac{1}{20}\)</span>, of a false positive. Therefore, for this experiment, let’s use:</p>
<ul>
<li><span class="math inline">\(\alpha = 0.05\)</span></li>
</ul>
<p>When we conduct the test, it will result in a <span class="math inline">\(p\)</span>-value. This is the chance that you would draw a sample with <em>this</em> large a difference, if the null-hypothesis were true. In other words, if there is no actual difference in bacteria in the air of your kitchen and living room, then what is the chance that you observed the difference of your experiment? If this chance is extremely small, then we reject the null-hypothesis.</p>
<p>Specifically:</p>
<ul>
<li>If <span class="math inline">\(p &lt; \alpha\)</span>, reject <span class="math inline">\(H_0\)</span>;</li>
<li>If <span class="math inline">\(p \geq \alpha\)</span>, there is insufficient evidence against <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p>An insignificant test does not demonstrate that there is no difference. It just means that your sample provides insufficient reason to reject the null-hypothesis. Nevertheless, the null-hypothesis is still only an assumption.</p>
</div>
<div id="chi-squared" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> The Chi-Squared Test<a href="your-own-experiment-i.html#chi-squared" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose we do the experiment and count:</p>
<ul>
<li>Kitchen: 21 kolonies;</li>
<li>Living room: 15 kolonies.</li>
</ul>
<p>Comparing observed to expected counts can be done with a <span class="math inline">\(\chi^2\)</span>-test (chi-squared). This test looks whether the proportion of colonies counted on the plate from the kitchen and living room are equal.</p>
<div id="how-does-the-chi-squared-test-work" class="section level3 hasAnchor" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> How Does the Chi-Squared Test Work?<a href="your-own-experiment-i.html#how-does-the-chi-squared-test-work" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As you’ll see in the next section, performing the test is really easy with <code>chisq.test()</code>.</p>
<p>Nevertheless, here I’ll explain what the test actually does, so you can see what it is we’re really doing. If you already know how it works, feel free to <a href="your-own-experiment-i.html#chisq">skip to the next section</a>.</p>
<p><strong>In short</strong>: A chi-squared test calculated the number <span class="math inline">\(\chi^2\)</span> as shown below, and then calculates a corresponding <span class="math inline">\(p\)</span>-value. If the <span class="math inline">\(p\)</span>-value is lower than <span class="math inline">\(\alpha\)</span>, then there is a significant difference in the colonies counted in the kitchen and living room.</p>
<ul>
<li><span class="math inline">\(\chi^2 = \displaystyle\sum_{i = 1}^k \frac{(\text{observed} - \text{expected})^2}{\text{expected}}\)</span></li>
</ul>
<p>The expected numbers are the numbers under the null-hypothesis. These are simply equal to the average count:</p>
<ul>
<li><span class="math inline">\(\text{expected} = \frac{21 + 15}{2} = 18\)</span></li>
</ul>
<p>Now we can calculate <span class="math inline">\(\chi^2\)</span>:</p>
<ul>
<li><span class="math inline">\(\chi^2 = \displaystyle\sum_{i = 1}^k \frac{(\text{obs.} - \text{exp.})^2}{\text{exp.}} = \frac{(\text{21} - \text{18})^2}{\text{18}} + \frac{(\text{15} - \text{18})^2}{\text{18}} = \frac{1}{2} + \frac{1}{2} = 1\)</span></li>
</ul>
<p>You don’t have to know how to estimate a <span class="math inline">\(p\)</span>-value from that number, but I can easily show it in a figure:</p>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>That is the chi-squared distribution with one degree of freedom (because we have two groups and calculated one value). This figure shows the distribution of values of <span class="math inline">\(\chi^2\)</span> that you would expect to find if the null-hypothesis were true. De largest chance is a value of <span class="math inline">\(\chi^2 = 0\)</span>, and after that, the probability density decreases. <strong>The <span class="math inline">\(p\)</span>-value answers the question: If the null-hypothesis is true, what is the chance of our <span class="math inline">\(\chi^2 = 1\)</span> or higher?</strong>.</p>
<p>The <span class="math inline">\(p\)</span>-value for <span class="math inline">\(\chi^2=1\)</span> is the surface area under the probability distribution from <span class="math inline">\(1\)</span> on:</p>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>That is <span class="math inline">\(31.7\%\)</span>, almost one third of the entire surface area, so we don’t have very convincing evidence against the null-hypothesis:</p>
<ul>
<li>If there is no difference in the population, the chance of <span class="math inline">\(\chi^2 \geq 1\)</span> is <span class="math inline">\(p = 0.317\)</span>.</li>
</ul>
<p>In this example, <span class="math inline">\(p &gt; \alpha\)</span>, so we don’t reject <span class="math inline">\(H_0\)</span>. In the report we would write that there is insufficient evidence to conclude a difference in bacteria in the kitchen and living room from this experiment.</p>
<p>To calculate this value yourself, you would have to evaluate the integral of the chi-squared distribution from <span class="math inline">\(1\)</span> to <span class="math inline">\(\infty\)</span>. <a href="https://en.wikipedia.org/wiki/Chi-square_distribution#Cumulative_distribution_function">I don’t recommend trying it by hand</a>. Fortunately, we have R:</p>
<p><small></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="your-own-experiment-i.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="dv">1</span>, <span class="at">df =</span> <span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="co"># df: two groups, one value estimated, so 2 - 1</span></span></code></pre></div>
<pre><code>## [1] 0.3173105</code></pre>
<p></small></p>
<p>This says: <span class="math inline">\(1\)</span> minus the chance of any value up till <span class="math inline">\(\chi^2=1\)</span>. And that is how we get <span class="math inline">\(0.317\)</span>.</p>
</div>
<div id="chisq" class="section level3 hasAnchor" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> Chi-Squared Test in R<a href="your-own-experiment-i.html#chisq" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you think the explanation so far is a lot, I don’t blame you. It takes quite a lot of background knowledge to understand a simple test. The explanation of how the chi-squared test works will not be part of the microbiology exam. Nevertheless, I wanted to include it here, so that you can read what is going on when you use this test. Namely, it can all be done in a few seconds in R:</p>
<p><small></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="your-own-experiment-i.html#cb19-1" aria-hidden="true" tabindex="-1"></a>example <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">15</span>)</span>
<span id="cb19-2"><a href="your-own-experiment-i.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(example)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  example
## X-squared = 1, df = 1, p-value = 0.3173</code></pre>
<p></small></p>
<p>That is all there is to it:</p>
<ul>
<li>R calculated a value of <span class="math inline">\(\chi^2 = 1\)</span>;</li>
<li>It then says <code>df = 1</code>, which means there is one degree of freedom: <small><span class="math inline">\(\text{number of independent observations} - \text{number of estimated parameters} = 2 - 1 = 1\)</span></small>;</li>
<li>Those things combined yield a <span class="math inline">\(p\)</span>-value of <code>0.3173</code>.</li>
</ul>
</div>
</div>
<div id="microbiologyex" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Exercises<a href="your-own-experiment-i.html#microbiologyex" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Open the R markdown file “Exercises.Rmd” and answer the questions. The questions themselves are included here.</p>
<div id="performing-a-chi-squared-test" class="section level3 hasAnchor" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Performing a Chi-Squared Test<a href="your-own-experiment-i.html#performing-a-chi-squared-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose another student performs the same experiment and counts:</p>
<ul>
<li>Kitchen: 36 colonies;</li>
<li>Living room: 21 colonies.</li>
</ul>
<p>Use <span class="math inline">\(\alpha = 0.05\)</span> and conduct a <span class="math inline">\(\chi^2\)</span>-test for these data. You can use the code <a href="your-own-experiment-i.html#chisq">above</a> and adapt it.</p>
</div>
<div id="compare2" class="section level3 hasAnchor" number="5.6.2">
<h3><span class="header-section-number">5.6.2</span> Comparing Two Students<a href="your-own-experiment-i.html#compare2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we want to see if the counts are significantly different between two students:</p>
<p><small></p>
<table style="width:50%; margin-left: auto; margin-right: auto;" class="table">
<caption>
<span id="tab:unnamed-chunk-30">Table 5.1: </span><span class="math inline">\(2 \times 2\)</span> contingency table of student 1 &amp; 2.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Kitchen
</th>
<th style="text-align:center;">
Living room
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Student 1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
Student 2
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
21
</td>
</tr>
</tbody>
</table>
<p></small></p>
<p>All a <span class="math inline">\(\chi^2\)</span>-test does is compare observed to expected counts. You can apply this to contingency tables too. The test then determines the difference in the proportion of colonies in the kitchen and living room for student 1 and 2. You don’t have to calculate the expected counts by hand, but an explanation is given below for those interested.<span class="math inline">\(^\dagger\)</span></p>
<p>In R, all you have to do is put the data in a <span class="math inline">\(2 \times 2\)</span> matrix, for example using <code>rbind</code> (row bind):</p>
<p><small></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="your-own-experiment-i.html#cb21-1" aria-hidden="true" tabindex="-1"></a>Student1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">15</span>) </span>
<span id="cb21-2"><a href="your-own-experiment-i.html#cb21-2" aria-hidden="true" tabindex="-1"></a>Student2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">36</span>, <span class="dv">21</span>)</span>
<span id="cb21-3"><a href="your-own-experiment-i.html#cb21-3" aria-hidden="true" tabindex="-1"></a>ContingencyTable <span class="ot">&lt;-</span> <span class="fu">rbind</span>(Student1, Student2)             <span class="co"># Create a 2x2 matrix</span></span>
<span id="cb21-4"><a href="your-own-experiment-i.html#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(ContingencyTable) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Kitchen&quot;</span>, <span class="st">&quot;Living Room&quot;</span>) <span class="co"># Add column names</span></span>
<span id="cb21-5"><a href="your-own-experiment-i.html#cb21-5" aria-hidden="true" tabindex="-1"></a>ContingencyTable                                          <span class="co"># Print the result</span></span></code></pre></div>
<pre><code>##          Kitchen Living Room
## Student1      21          15
## Student2      36          21</code></pre>
<p></small></p>
<p>Then, simply use <code>chisq.test()</code> on the contingency table:</p>
<p><small></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="your-own-experiment-i.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(ContingencyTable)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  ContingencyTable
## X-squared = 0.060876, df = 1, p-value = 0.8051</code></pre>
<p></small></p>
<p>This results in a <span class="math inline">\(p\)</span>-value for the null-hypothesis:</p>
<ul>
<li>The difference in kitchen and living room is independent of which student performs the experiment.</li>
</ul>
<p>With <span class="math inline">\(\alpha = 0.05\)</span>, what would you conclude?</p>
<hr />
<p><span class="math inline">\(^\dagger:\)</span> <small>For a contingency table, the expected counts are what you would expect if the relative counts of student 1 did not differ from student 2, proportional to their total counts:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-33">Table 5.2: </span>Observed and expected frequencies for a <span class="math inline">\(2 \times 2\)</span> contingency table.
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Observed
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Expected
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Kitchen
</th>
<th style="text-align:center;">
Living room
</th>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
Kitchen
</th>
<th style="text-align:center;">
Living room
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Student 1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
<span class="math inline">\(\frac{(21+36)(21+15)}{21+36+15+21}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\frac{(15+21)(21+15)}{21+36+15+21}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Student 2
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
<span class="math inline">\(\frac{(21+36)(36+21)}{21+36+15+21}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\frac{(15+21)(36+21)}{21+36+15+21}\)</span>
</td>
</tr>
</tbody>
</table>
<p></small></p>
</div>
<div id="comparing-two-other-students" class="section level3 hasAnchor" number="5.6.3">
<h3><span class="header-section-number">5.6.3</span> Comparing Two Other Students<a href="your-own-experiment-i.html#comparing-two-other-students" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Conduct the same test for the difference between two students using the real experimental data from your class. For example, you could compare the results with your lab partner’s. You can use the <a href="your-own-experiment-i.html#compare2">the previous exercise</a> as an example.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="6">
<li id="fn6"><p><small>An experimental unit is the smallest division of the sample that is still an independent part. Some example: In clinical trials, patients are experimental units; In a study on fertilizer effectiveness, plants are experimental units; In an experiment on antibiotic effectiveness, a single agar plate is an experimental unit.</small><a href="your-own-experiment-i.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p><small>A false positive occurs when you conclude a significant difference, even though there is no real difference in the underlying population from which the sample came. <strong>Example 1</strong>: If we conclude a medicine works significantly better than a placebo in the <em>sample</em>, but it does not actually work on average in the population, then we have a false positive for the effect of the medicine. <strong>Example 2</strong>: Say we estimate the ratio of black to white sheep in a large farm by drawing a random sample. A false postive would occur if in the sample, the ratio differed significantly from <span class="math inline">\(1 : 1\)</span>, even though it does not in the whole farm. False positives are also called type I errors.</small><a href="your-own-experiment-i.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p><small>The population here consists of all possible samples of air from your kitchen and living room.</small><a href="your-own-experiment-i.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p><small>Of course, in reality a diagnostic test for cancer is followed by further diagnosis to minimize the probability of this scenario.</small><a href="your-own-experiment-i.html#fnref9" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="bradford-assay.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sepia.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Biostatistics.pdf", "Biostatistics.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
